"""empty message

Revision ID: 766d1d1f2b1c
Revises: 175b9adcbf0c
Create Date: 2020-01-30 16:15:42.639259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766d1d1f2b1c'
down_revision = '175b9adcbf0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
